### ISSUE TITLE
The images have  4 channels

### ISSUE THREAD

**Issue by AashishV** [clic-lab/nlvr#2]
The given images have 4 colour channels and the last channel looks like this,

![screenshot from 2017-07-14 13-31-06](https://user-images.githubusercontent.com/3125480/28210669-d60c641a-6898-11e7-88a0-046b568f3256.png)

Is there any particular reason for this?

**Comment by alsuhr-c** [comment]
What software are you using to view 4 channels? Is this CMYK? You should be able to interpret the images as 3-channel (RGB).

**Comment by AashishV** [comment]
```
from PIL import Image
import numpy as np

img_filename = '../../../Dataset/nlvr/train/images/1/train-1196-0-0.png'

img = Image.open(img_filename)
print(np.array(img).shape)
```

This gives an output as (100, 400, 4).

So, I am using the below snippet:

```
from PIL import Image
import numpy as np

img_filename = '../../../Dataset/nlvr/train/images/1/train-1196-0-0.png'

img = Image.open(img_filename).convert('RGB')
print(np.array(img).shape)
```

This gives me an output of (100, 400, 3) but I have to divide them by 255 to make the values lie in between 0 and 1.

**Comment by alsuhr-c** [comment]
I'm not very familiar with PIL, and in our code we use scipy imread (which calls PIL and gives us four channels -- we throw away the last channel). The last channel value is 255 for us, so I would guess this is some kind of alpha value. I'd suggest ignoring this channel because the values are all the same for each example. I'd also suggest dividing by 255. But you can investigate with PIL to see if it can do all of this by default for you. Does this answer your question?

**Comment by AashishV** [comment]
Yes, this does answer my question. Thank you for the quick reply.
