### ISSUE TITLE
Label distributions

### ISSUE THREAD

**Issue by pdasigi** [clic-lab/nlvr#8]
I am looking at the distributions of labels for sentences across structured representations, and wanted to check if my observations are correct. I grouped structured representations by gathering those in examples whose identifiers have the same "m" values, where each identifier is of the form "m-n".

I imagined I would find each sentence occurring with four different structured representations, two in which it is true and two in which it is false. However, I see that
1) Only 3358 out of 3696 sentences in train, dev and test occur with 4 different structured representations, and others have less than four structures.
2) Only 2176 out of the 3696 sentences have equal numbers of true and false labels.
3) 465 out of the 3696 sentences have all true or all false labels.

I can see how (1) may have happened during post-processing to remove examples with low agreement, but I am not sure about (2) and (3). Please let me know if this is expected.

Thanks!

**Comment by alsuhr-c** [comment]
Regarding the distributions:

1. Yes, this is due to removing examples with low agreement.
2. The validation process we ran was able to completely re-label image/sentence pairs as true or false. We didn't consider the original position of the image when labeling it. In practice, 8.2% of examples had a different label than the one inferred by the original position. This number (2176/3696) could also be confounded by the fact that not all of those sentences have 4 examples. I'm not sure what the distribution of labels is if you look at sentences with four images (of the 3358 you identified).
3. This is also caused by the re-labeling during validation, but also may be due to the number of images for those 496 sentences. It's possible that many of those 496 only have one or two associated images, which makes it more likely they will all have the same label. 

Also, I believe the identifier tells you the original position of the image in the four. If n = 0 or 1, then the original position was at the top (sentence should have been true); if n = 2 or 3, then the original position was at the bottom (sentence should have been false). 

Hope this helps.

**Comment by pdasigi** [comment]
That's helpful. Thanks!
